#!/bin/bash

black='\033[0;30m'
darkgray='\033[1;30m'
blue='\033[0;34m'
lightblue='\033[1;34m'
green='\033[0;32m'
lightgreen='\033[1;32m'
cyan='\033[0;36m'
lightcyan='\033[1;36m'
red='\033[0;31m'
lightred='\033[1;31m'
purple='\033[0;35m'
lightpurple='\033[1;35m'
orange='\033[0;33m'
yellow='\033[1;33m'
lightgrey='\033[0;37m'
white='\033[1;37m'

echo -e "${blue}Running the server in the backgound.$white"
if [ -d /vagrant ]; then
    cd /vagrant
fi

screen -dmS pythonstaticserver python -m SimpleHTTPServer 8000

echo -e "${blue}Started server at port 8000.$white"
