Vagrant.configure(2) do |config|

	config.vm.box = "ubuntu/trusty32"
	config.vm.provision :shell, path: "configure", privileged: false, keep_color: true
	config.vm.provision :shell, path: "run", privileged: false, keep_color: true, run: "always"
	config.vm.network "forwarded_port", guest: 8000, host: 9000

end
